tree_menu/app_menu/urls.py
from django.urls import path

from app_menu.views import draw_menu, index

app_name = 'app_menu'

urlpatterns = [
    path('', index, name='main_menu'),
    path('<path:path>/', draw_menu, name='draw_menu'),
]

tree_menu/tree_menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_menu.urls', namespace='app_menu')),
]

tree_menu/app_menu/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название меню')
    url = models.SlugField(max_length=255, verbose_name='Ссылка на меню')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'


class Item(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название пункта меню')
    url = models.SlugField(max_length=255, verbose_name='Ссылка на пункт меню')
    menu = models.ForeignKey(Menu, blank=True, related_name='items',
                             on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                               null=True, blank=True, related_name='children')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'

tree_menu/app_menu/views.py
from django.shortcuts import render

from app_menu.models import Menu


def index(request):
    return render(request, 'app_menu/index.html',
                  {'menus_name': Menu.objects.all()})


def draw_menu(request, path):
    slug = (path.split('/'))
    return render(request, 'app_menu/menu.html', {'menu_name': slug[0]})

tree_menu/app_menu/templates/app_menu/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>

tree_menu/app_menu/templates/app_menu/index.html
{% extends 'app_menu/base.html' %}

{% block title %} Меню {% endblock %}
{% load tree_menu_tags %}

{% block content %}
{% if menus_name %}
        {% for menu in menus_name %}
            <li><a href={% url 'app_menu:draw_menu' menu.url %}>{{ menu }}</li>
        {% endfor %}
{% endif %}
{% endblock %}

tree_menu/app_menu/templates/app_menu/menu.html
{% extends 'app_menu/base.html' %}

{% block title %} Дерево меню {{ menu_name }} {% endblock %}


{% load tree_menu_tags %}

{% block content %}
{% if menu_name %}
  {% draw_menu menu_name %}
{% endif %}
{% endblock %}